# Generated by Django 3.0.3 on 2020-02-19 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_auto_20200219_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wishes.List'),
        ),
    ]
