# Generated by Django 3.0.3 on 2020-02-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0005_auto_20200219_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
