# Generated by Django 3.0.3 on 2020-02-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0007_auto_20200220_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wish',
            name='purchased_by',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
